[package]
name = "helper"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shared-contracts = { path = "../shared-contracts" }
windows = { version = "0.62", features = [
    "Foundation",
    "Networking_Connectivity",
] }
